crd_koleksi_tokoh/urls.py
from django.urls import path

from . import views

app_name = 'crd_koleksi_tokoh'

urlpatterns = [
    path('create', views.create_koleksi_tokoh, name='create_koleksi_tokoh'),
    path('read', views.read_koleksi_tokoh, name='read_koleksi_tokoh'),
    path('delete/<str:id_koleksi>', views.delete_koleksi_tokoh, name='delete_koleksi_tokoh')
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.landing_page, name='login'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('admin_homepage/', views.admin_homepage, name='admin_homepage'),
    path('pemain_homepage/', views.pemain_homepage, name='pemain_homepage'),
]

the_cims/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('tokoh/', include('tokoh.urls')),
    path('barang/', include('barang.urls')),
    path('misi_utama/', include('misi_utama.urls')),
    path('warna_kulit/', include('warna_kulit.urls')),
    path('level/', include('level.urls')),
    path('menggunakan_apparel/', include('menggunakan_apparel.urls')),
    path('kategori_apparel/', include('crd_kategori_apparel.urls')),
    path('koleksi/', include('crud_koleksi.urls')),
    path('koleksi_tokoh/', include('crd_koleksi_tokoh.urls')),
    path('pekerjaan/', include('pekerjaan.urls')),
    path('menjalankan_misi_utama/', include('menjalankan_misi_utama.urls')),
    path('makanan/', include('makanan.urls')),
    path('makan/', include('makan.urls')),


]

crd_koleksi_tokoh/models.py
from django.db import models

# Create your models here.

crd_koleksi_tokoh/views.py
from django.shortcuts import render, HttpResponse, redirect
from utils.query import query
from home.views import get_session_data, is_authenticated, login

# Create your views here.


def create_koleksi_tokoh(request):
    if not is_authenticated(request):
        return login(request)

    if request.session['role'] != 'pemain':
        return HttpResponse("Hanya pemain yang dapat membuat koleksi tokoh")

    username = request.session['username']

    if request.method == "POST":

        id_koleksi = request.POST["koleksi"]
        nama_tokoh = request.POST["tokoh"]

        query(f"""
                INSERT INTO KOLEKSI_TOKOH
                VALUES('{id_koleksi}', '{username}', '{nama_tokoh}')
            """)

        return redirect("crd_koleksi_tokoh:read_koleksi_tokoh")

    list_nama_tokoh = query(f"""
        SELECT nama FROM TOKOH WHERE username_pengguna = '{username}'
    """)

    list_koleksi = query(f"""
        SELECT id, harga FROM KOLEKSI
    """)

    context = {
        "list_nama_tokoh": list_nama_tokoh,
        "list_koleksi": list_koleksi
    }

    return render(request, 'pemain_create_koleksi_tokoh.html', context)


def read_koleksi_tokoh(request):
    if not is_authenticated(request):
        return login(request)

    if request.session['role'] == "admin":
        list_koleksi_tokoh = query("SELECT * FROM KOLEKSI_TOKOH")

        data = get_session_data(request)

        data['list_koleksi_tokoh'] = list_koleksi_tokoh
        return render(request, 'admin_read_koleksi_tokoh.html', data)
    else:
        list_koleksi_tokoh = query(
            f"SELECT * FROM KOLEKSI_TOKOH WHERE username_pengguna = '{request.session['username']}'")

        list_deletable = query(f"""
            SELECT DISTINCT id_koleksi from KOLEKSI_TOKOH
            WHERE id_koleksi NOT IN (
                SELECT id_rambut from TOKOH
                WHERE username_pengguna = '{request.session['username']}'
            ) AND id_koleksi IN (
                SELECT id_koleksi from RAMBUT
            ) 
            UNION 
            SELECT DISTINCT id_koleksi from KOLEKSI_TOKOH
            WHERE id_koleksi NOT IN (
                SELECT id_mata from TOKOH
                WHERE username_pengguna = '{request.session['username']}'
            ) AND id_koleksi IN (
                SELECT id_koleksi from MATA
            )
            UNION 
            SELECT DISTINCT id_koleksi from KOLEKSI_TOKOH
            WHERE id_koleksi NOT IN (
                SELECT id_rumah from TOKOH
                WHERE username_pengguna = '{request.session['username']}'
            ) AND id_koleksi IN (
                SELECT id_koleksi from RUMAH
            )
            UNION 
            SELECT DISTINCT id_koleksi from KOLEKSI_TOKOH
            WHERE id_koleksi NOT IN (
                SELECT id_barang from MENGGUNAKAN_BARANG
                WHERE username_pengguna = '{request.session['username']}'
            ) AND id_koleksi IN (
                SELECT id_koleksi from BARANG
            )
            UNION 
            SELECT DISTINCT id_koleksi from KOLEKSI_TOKOH
            WHERE id_koleksi NOT IN (
                SELECT id_koleksi from MENGGUNAKAN_APPAREL
                WHERE username_pengguna = '{request.session['username']}'
            ) AND id_koleksi IN (
                SELECT id_koleksi from APPAREL
            )
        """)

        data = get_session_data(request)

        data['list_koleksi_tokoh'] = list_koleksi_tokoh
        data['list_deletable'] = list(map(lambda x: x[0], list_deletable))
        
        return render(request, 'pemain_read_koleksi_tokoh.html', data)

def delete_koleksi_tokoh(request, id_koleksi):
    if not is_authenticated(request):
        return login(request)

    if request.session['role'] != "pemain":
        return HttpResponse("Hanya pemain yang dapat menghapus koleksi tokoh")

    query(f"""
        DELETE FROM KOLEKSI_TOKOH
        WHERE id_koleksi = '{id_koleksi}'
    """)

    return redirect("crd_koleksi_tokoh:read_koleksi_tokoh")

crd_koleksi_tokoh/templates/admin_read_koleksi_tokoh.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include 'navbar_admin.html' %}
    <h1 class="text-center mt-3">LIST KOLEKSI TOKOH</h1>
    <div class="container">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Username Pengguna</th>
            <th scope="col">Tokoh</th>
            <th scope="col">Id Koleksi</th>
          </tr>
        </thead>
        {% for k in list_koleksi_tokoh %}
        <tbody>
          <tr>
            <td>{{k.username_pengguna}}</td>
            <td>{{k.nama_tokoh}}</td>
            <td>{{k.id_koleksi}}</td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
    </div>
  </body>
</html>

crd_koleksi_tokoh/templates/pemain_create_koleksi_tokoh.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Create Kategori Apparel</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include 'navbar_pemain.html' %}

    <h1 class="text-center mt-3">FORM BUAT KOLEKSI TOKOH</h1>
    <form
      method="POST"
      class="container mt-5"
      id="admin_create_kategori_apparel_form"
    >
      {% csrf_token %}

      <div class="mb-3">
        <label class="form-label">Nama Tokoh: </label>
        <select name="tokoh" required class="form-select" aria-label="Pilih tokoh">
          {% for tokoh in list_nama_tokoh %}
            <option value="{{ tokoh.nama }}">{{ tokoh.nama }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="mb-3">
        <label class="form-label">ID Koleksi: </label>
        <select name="koleksi" class="form-select" aria-label="Pilih ID Koleksi">
          {% for koleksi in list_koleksi %}
            <option value="{{ koleksi.id }}">Rp {{ koleksi.harga }} (ID: {{koleksi.id}})</option>
          {% endfor %}
        </select>
      </div>

      <button type="submit" class="btn btn-primary mx-auto d-block">
        Simpan
      </button>
    </form>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
      crossorigin="anonymous"
    ></script>
  </body>
  <script>
    $("#pengguna_create_koleksi_tokoh_form").submit((e) => {
      const categoryValue = $("input[name='kategori']").val();
      if (categoryValue === "") {
        e.preventDefault();
        alert(
          "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"
        );
      }
    });
  </script>
</html>

crd_koleksi_tokoh/templates/pemain_read_koleksi_tokoh.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include 'navbar_pemain.html' %}
    <h1 class="text-center mt-3">LIST KOLEKSI TOKOH</h1>
    <div class="container">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Tokoh</th>
            <th scope="col">Id Koleksi</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        {% for k in list_koleksi_tokoh %}
        <tbody>
          <tr>
            <td>{{k.nama_tokoh}}</td>
            <td>{{k.id_koleksi}}</td>
            <td>
              {% if k.id_koleksi in list_deletable %}
              <div class="d-grid gap-2 d-md-block">
                <a href="{% url 'crd_koleksi_tokoh:delete_koleksi_tokoh' k.id_koleksi %}" class="btn btn-outline-success"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-currency-dollar" viewBox="0 0 16 16">
                  <path d="M4 10.781c.148 1.667 1.513 2.85 3.591 3.003V15h1.043v-1.216c2.27-.179 3.678-1.438 3.678-3.3 0-1.59-.947-2.51-2.956-3.028l-.722-.187V3.467c1.122.11 1.879.714 2.07 1.616h1.47c-.166-1.6-1.54-2.748-3.54-2.875V1H7.591v1.233c-1.939.23-3.27 1.472-3.27 3.156 0 1.454.966 2.483 2.661 2.917l.61.162v4.031c-1.149-.17-1.94-.8-2.131-1.718H4zm3.391-3.836c-1.043-.263-1.6-.825-1.6-1.616 0-.944.704-1.641 1.8-1.828v3.495l-.2-.05zm1.591 1.872c1.287.323 1.852.859 1.852 1.769 0 1.097-.826 1.828-2.2 1.939V8.73l.348.086z"/>
                </svg> Jual</a>
              </div>
              {% endif %}
            </td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
    </div>
  </body>
</html>